name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite, dom
          coverage: none
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare environment
        run: |
          cp .env.example .env || true
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          {
            echo "DB_CONNECTION=sqlite";
            echo "DB_DATABASE=database/database.sqlite";
          } >> .env
          php artisan key:generate

      - name: Migrate database
        run: php artisan migrate --force

      - name: Check code style (Pint)
        run: ./vendor/bin/pint --test

      - name: Run tests
        run: php artisan test --no-ansi

      - name: Install Node dependencies
        run: npm install

      - name: Build frontend (Vite)
        run: npm run build

